name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BEEHIIV_API_KEY: ${{ secrets.BEEHIIV_API_KEY }}
  BEEHIIV_PUBLICATION_ID: ${{ secrets.BEEHIIV_PUBLICATION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy beehiiv-integration \
          --runtime=python311 \
          --trigger=http \
          --allow-unauthenticated \
          --source=. \
          --entry-point=main \
          --set-env-vars="BEEHIIV_API_KEY=${{ secrets.BEEHIIV_API_KEY }},BEEHIIV_PUBLICATION_ID=${{ secrets.BEEHIIV_PUBLICATION_ID }}"
